name: "Release Generator"

on:
  push:
    branches: [ master ]

jobs:
  test:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - run: echo "previous_tag=$(git describe --tags --abbrev=0 2>/dev/null || echo '')" >> $GITHUB_ENV

    - name: Generate Changelog
      id: changelog
      uses: jaywcjlove/changelog-generator@main
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        head-ref: ${{steps.changelog.outputs.version}}
        original-markdown: true
        filter: '[R|r]elease[d]\s+[v|V]\d(\.\d+){0,2}'

    - run: echo "outputs.changelog - ${{ steps.changelog.outputs.changelog }}"
    - run: echo "outputs.tag - ${{ steps.changelog.outputs.tag }}"
    - run: echo "outputs.branch - ${{ steps.changelog.outputs.branch }}"
    - run: echo "outputs.compareurl - ${{ steps.changelog.outputs.compareurl }}"
    - run: echo "outputs.version - ${{ steps.changelog.outputs.version }}"

    - name: Generate Changelog (path test)
      id: changelog_path
      uses: jaywcjlove/changelog-generator@main
      with:
        path: ./.github/workflows/changelog.yml
        token: ${{ secrets.GITHUB_TOKEN }}
        head-ref: ${{steps.changelog.outputs.version}}
        original-markdown: true
        filter: '[R|r]elease[d]\s+[v|V]\d(\.\d+){0,2}'

    - name: Generate Changelog (outputs.changelog)
      run: echo "${{ steps.changelogEmoji.outputs.changelog }}"

    - name: Generate Changelog(main)
      uses: jaywcjlove/changelog-generator@main
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        custom-emoji: 'chore💻'
        filter: '[R|r]elease[d]\s+[v|V]\d(\.\d+){0,2}'

    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        name: ${{ steps.changelog.outputs.version }}
        tag: ${{ steps.changelog.outputs.version }}
        body: |
          ${{ steps.changelog.outputs.compareurl }}
            
          ${{ steps.changelog.outputs.changelog }}
          
